"""
hazard_engine/constants.py
"""
DECAY_DISTANCE_KM = 50.0
DECAY_DEPTH_KM = 35.0
MAGNITUDE_DAMAGE_COEFF = 1.2
DECAY_AGE_YEARS = 15.0

FAULT_VERY_HIGH_LIMIT = 10.0
FAULT_HIGH_LIMIT = 30.0
FAULT_MODERATE_LIMIT = 75.0
